# Setup
title:        Rob Firth Research and Analytics
tagline:      What does this all mean, anyway?
baseurl:      ""
paginate:     1

# About/contact
author:       berto
  name:       Rob Firth
  url:        http://robfirth.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
