# Setup
title:        Welcome
tagline:      I'm Rob, and this is my website - Astronomy, Data Analytics and Everything Else.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Robert firth
  url:        http://robfirth.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
